/**
 * Local domain facts used by the verifier. These lists are intentionally kept
 * in code so no message-level data is persisted or fetched to classify common
 * provider domains.
 */

export const FREEMAIL_DOMAINS = new Set([
  'aol.com',
  'fastmail.com',
  'gmail.com',
  'gmx.com',
  'gmx.de',
  'hey.com',
  'hotmail.com',
  'icloud.com',
  'inbox.com',
  'live.com',
  'mail.com',
  'mail.ru',
  'me.com',
  'msn.com',
  'outlook.com',
  'pm.me',
  'proton.me',
  'protonmail.com',
  'qq.com',
  'tutanota.com',
  'yahoo.co.uk',
  'yahoo.com',
  'yandex.com',
  'yandex.ru',
  'zoho.com',
]);

export const DISPOSABLE_DOMAINS = new Set([
  '10minutemail.com',
  '20minutemail.com',
  'anonbox.net',
  'burnermail.io',
  'byom.de',
  'dispostable.com',
  'emailondeck.com',
  'fakeinbox.com',
  'getairmail.com',
  'guerrillamail.com',
  'guerrillamail.net',
  'maildrop.cc',
  'mailinator.com',
  'mailnesia.com',
  'mintemail.com',
  'moakt.com',
  'sharklasers.com',
  'spam4.me',
  'temp-mail.org',
  'tempmail.com',
  'tempmailo.com',
  'throwawaymail.com',
  'trashmail.com',
  'yopmail.com',
]);

export const TOP_BRAND_DOMAINS = [
  'adobe.com',
  'amazon.com',
  'americanexpress.com',
  'apple.com',
  'bankofamerica.com',
  'bestbuy.com',
  'chase.com',
  'citi.com',
  'cloudflare.com',
  'coinbase.com',
  'costco.com',
  'docusign.com',
  'dropbox.com',
  'ebay.com',
  'facebook.com',
  'fedex.com',
  'github.com',
  'google.com',
  'instagram.com',
  'linkedin.com',
  'microsoft.com',
  'netflix.com',
  'office.com',
  'paypal.com',
  'quickbooks.intuit.com',
  'salesforce.com',
  'shopify.com',
  'slack.com',
  'stripe.com',
  'target.com',
  'tesla.com',
  'ups.com',
  'usps.com',
  'walmart.com',
  'wellsfargo.com',
  'x.com',
  'zellepay.com',
  'zoom.us',
];

export const RDAP_BOOTSTRAP: Record<string, string> = {
  ai: 'https://rdap.identitydigital.services/rdap/domain/',
  app: 'https://rdap.nic.google/domain/',
  biz: 'https://rdap.identitydigital.services/rdap/domain/',
  ca: 'https://rdap.ca.fury.ca/rdap/domain/',
  co: 'https://rdap.nic.co/domain/',
  com: 'https://rdap.verisign.com/com/v1/domain/',
  de: 'https://rdap.denic.de/domain/',
  dev: 'https://rdap.nic.google/domain/',
  fr: 'https://rdap.nic.fr/domain/',
  info: 'https://rdap.identitydigital.services/rdap/domain/',
  io: 'https://rdap.nic.io/domain/',
  me: 'https://rdap.nic.me/domain/',
  net: 'https://rdap.verisign.com/net/v1/domain/',
  nl: 'https://rdap.sidn.nl/domain/',
  org: 'https://rdap.publicinterestregistry.org/rdap/domain/',
  uk: 'https://rdap.nominet.uk/uk/domain/',
  us: 'https://rdap.nic.us/domain/',
};
